# use and official image of node.js runtime
FROM  node:22-alpine

# set working directory
WORKDIR /app
# copy all package.json file in the workign directory
COPY package*.json ./
# install dependencies
RUN npm install
# copy all files
COPY . .
# expose port
ENV PORT=3000
# run the application
CMD ["node", "index.js"]